
platform :ios, '10.0'

plugin 'cocoapods-binary'
use_frameworks!
enable_bitcode_for_prebuilt_frameworks!

# https://www.ralfebert.de/ios/blog/cocoapods-clean-input-output-files/
install! 'cocoapods', :disable_input_output_paths => true


target 'BAKit_Example' do
  pod 'BAKit', :path => '../', :binary => false
  pod 'Firebase/Core', '~> 5.0', :binary => true
  pod 'Firebase/Messaging', :binary => true
  
  target 'BAKit_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
      cflags << '-fembed-bitcode'
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
  end
end
