
platform :ios, '10.0'

plugin 'cocoapods-binary'
use_frameworks!

target 'AdDrop' do
  pod 'BAKit', :path => '../'
  
  pod 'Firebase/Core', '~> 5.0'
  pod 'Firebase/Messaging'

  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.4'
  
  pod 'MaterialComponents'
  
  target 'AdDrop_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
      cflags << '-fembed-bitcode'
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
  end
end
